on:
  workflow_call:

jobs:
  update:
    name: Delete removed packages
    runs-on: ubuntu-latest
    steps:
      - name: Find and delete packages
        uses: tempbioc/delete-packages@master
        with:
          universe: ${{ github.event.repository.name }}
        env:
          CRANLIKEPWD: ${{ secrets.CRANLIKEPWD }}
          GITHUB_PAT: ${{ secrets.GHPAT }}
